### ISSUE TITLE
React objects

### ISSUE THREAD

**Issue by mhc297** [Projekt3/Projekt3#44]
Our functionality requires building text fields in react that will be populated by an object from an external api (similar to Bobby’s omdb api lab).
 
We are able to call the api and save the object in state to be passed down to the relevant components and display the highest level fields on the page (i.e., object.name). But when we try to drill down into the object further in the console (i.e. object.venues.name), the page crashes, receiving an error that either the server cannot find the responsible component (not the issue) or an error that it “cannot find the field name of undefined” (although we do not get this error when calling object.name). 

<img width="690" alt="screen shot 2016-11-27 at 3 38 13 pm" src="https://cloud.githubusercontent.com/assets/21985416/20651682/8e0e1ae0-b4b7-11e6-850b-34a68d1cf5b8.png">

<img width="1438" alt="screen shot 2016-11-27 at 3 35 28 pm" src="https://cloud.githubusercontent.com/assets/21985416/20651684/95abeb88-b4b7-11e6-8f2d-3fe53dccf1b6.png">

**Comment by mhc297** [comment]
@gittheking, @jasonseminara, @trevorpreston, @rapala61, @irwintsay

**Comment by rapala61** [comment]
want to chat?

**Comment by mhc297** [comment]
Yeah whenever you have a moment
